### ISSUE TITLE
ios reader applications does not install in Calibre 2.0

### ISSUE THREAD

**Issue by redjawriter** [Philantrop/calibre-ios-reader-applications#105]
Installed Calibre 2.0 yesterday, and iOS reader applications plugin will not install. I have followed all the proper steps, but it will not install. I have had it running right up until this version of Calibre. It looks as though it's looking for Qt4, but Calibre 2.0 is using Qt5. 

Here's the error message.

calibre, version 2.0.0
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/dialogs/plugin_updater.py", line 712, in _install_clicked
  File "site-packages/calibre/customize/ui.py", line 379, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 53, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 197, in load
  File "lib/python2.7/importlib/__init__.py", line 37, in import_module
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.**init**", line 43, in <module>
ImportError: No module named PyQt4.Qt

**Comment by stephenfleming6** [comment]
How would I delete that folder? Can't find it in my Calibre desktop files (OS X). Thanks!

**Comment by gwynevans** [comment]
Look in /Users/<username>/Library/Preferences/calibre/plugins/ but note that the Library folder may not be visible in Finder but if you use Go/Go to Folder, that should work.
