### ISSUE TITLE
iOS Reader Applications (1.4.3) cannot be customized by Calibre 2.1.0

### ISSUE THREAD

**Issue by d-a-v-i-d-j** [Philantrop/calibre-ios-reader-applications#113]
Using Calibre v2.1 and just installed v1.4.3 of the iOS reader.  When trying to customize the plugin for Marvin, I get the following error:

calibre, version 2.1.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name ConfigWidget

calibre 2.1  isfrozen: True is64bit: True
Darwin-13.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '13.4.0', 'Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64')
Python 2.7.8
OSX: ('10.9.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: Marvin XD && iOS reader applications
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 292, in customize_plugin
  File "site-packages/calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "site-packages/calibre/customize/**init**.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.**init**", line 493, in config_widget
ImportError: cannot import name ConfigWidget

**Comment by hashier** [comment]
Worked for me as well
