### ISSUE TITLE
unable to connect to idevice

### ISSUE THREAD

**Issue by ceekoke** [Philantrop/calibre-ios-reader-applications#139]
I'm getting the message "unable to connect to idevice"  Have never had a problem before - last connected a couple of weeks ago.  Tried installing new plug in but get message "import error no module named pyqt4.Qt"  Don't know if outdated plugin is problem?  Thanks
calibre, version 2.5.0
iOS reader applications: Unable to connect to iDevice
calibre, version 2.5.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4

calibre 2.5  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && iOS reader applications
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\iOS_reader_applications_resources\widgets\main_ui.py", line 10, in <module>
ImportError: No module named PyQt4

**Comment by Philantrop** [comment]
Go to Preferences | Advanced | Plugins | Device Interface plugins, select iOS reader applications.
Click Remove plugin.
Click Apply.
Go to Preferences | Advanced | Miscellaneous, click Open calibre configuration directory.
Open the plugins folder.
Delete iOS reader applications.json.
Delete the iOS_reader_applications_resources folder.
Restart calibre.
Then try installing the plugin(s) again.
