### ISSUE TITLE
iOS Customize Plugin Error: ImportError: No module named PyQt4

### ISSUE THREAD

**Issue by bizbox** [Philantrop/calibre-ios-reader-applications#140]
MacBookPro 10.95; iPad Retina 64GB Wifi; iOS 8.0.2; 

calibre, version 2.6.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4

calibre 2.6  isfrozen: True is64bit: True
Darwin-13.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '13.4.0', 'Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64')
Python 2.7.8
OSX: ('10.9.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: iOS reader applications
Traceback (most recent call last):
  File "site-packages/calibre/gui2/dialogs/plugin_updater.py", line 789, in _configure_clicked
  File "site-packages/calibre/customize/__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "/Users/sysadmin/Library/Preferences/calibre/plugins/iOS_reader_applications_resources/widgets/main_ui.py", line 10, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

**Comment by Philantrop** [comment]
As for the configuration issue:

Go to Preferences | Advanced | Plugins | Device Interface plugins, select iOS reader applications.
Click Remove plugin.
Click Apply.
Go to Preferences | Advanced | Miscellaneous, click Open calibre configuration directory.
Open the plugins folder.
Delete iOS reader applications.json.
Delete the iOS_reader_applications_resources folder.
Restart calibre.
Then try installing the plugin(s) again.

As for the unrecognised iPad Air 2: Fixed since Version 1.4.6 - 1 January 2015
