### ISSUE TITLE
Calibre not allowing iOS Reader Extension to be configured for Marvin

### ISSUE THREAD

**Issue by shrahman** [Philantrop/calibre-ios-reader-applications#141]
Cannot access the extension customization after updating calibre and extensions too... have tried the suggestions for trouble shooting, but to no avail...

_________________

calibre, version 2.7.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4

calibre 2.7  isfrozen: True is64bit: True
Darwin-14.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.0.0', 'Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64')
Python 2.7.8
OSX: ('10.10', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: iOS reader applications && Marvin XD
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 289, in double_clicked
  File "site-packages/calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages/calibre/customize/zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "/Users/Shehriyar/Library/Preferences/calibre/plugins/iOS_reader_applications_resources/widgets/main_ui.py", line 10, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

**Comment by Philantrop** [comment]
Go to Preferences | Advanced | Plugins | Device Interface plugins, select iOS reader applications.
Click Remove plugin.
Click Apply.
Go to Preferences | Advanced | Miscellaneous, click Open calibre configuration directory.
Open the plugins folder.
Delete iOS reader applications.json.
Delete the iOS_reader_applications_resources folder.
Restart calibre.

Then try installing the plugin(s) again.
