### ISSUE TITLE
calibre unable to recognize idevice and install plugin failed

### ISSUE THREAD

**Issue by ceekoke** [Philantrop/calibre-ios-reader-applications#143]
Would really appreciate some help with this - Always so happy with Calibre before
Thanks

calibre, version 2.5.0
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 712, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 383, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 550, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 544, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 910, in initialize
  File "calibre_plugins.ios_reader_apps.__init__", line 1239, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice
 failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 544, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 910, in initialize
  File "calibre_plugins.ios_reader_apps.__init__", line 1239, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice

**Comment by Philantrop** [comment]
During installation of the plugin, no iDevice must be connected.
