### ISSUE TITLE
Unable to configure iOS reader applications (version 1.4.4) plugin

### ISSUE THREAD

**Issue by Sabertech** [Philantrop/calibre-ios-reader-applications#151]
When attempting to connect to Calibre and following the instructions to configure the preferred ios Reader (Marvin in my case), I attempted to use the customize plugin function.  I tried it twice and got different error messages.  

Other info:
After installing the plugin, I closed and reopened Calibre then tried to customize the plugin (without the iPad plugged in)
iTunes is version 12.0.1.26
When plugged in, iTunes does see / recognize the iPad.

First try:
--------------------------------------------------------------
calibre, version 2.10.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4

calibre 2.10 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: FanFictionDownLoader && FictionDB && Extract ISBN && iOS reader applications && Goodreads && Barnes & Noble && Fantastic Fiction Adults && Quality Check && Modify ePub && Fantastic Fiction && Marvin XD && Count Pages
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "C:\Users\Chris\AppData\Roaming\calibre\plugins\iOS_reader_applications_resources\widgets\main_ui.py", line 10, in <module>
ImportError: No module named PyQt4

Second try:
--------------------------------------------------------------
calibre, version 2.10.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name ConfigWidget

calibre 2.10 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.8
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: FanFictionDownLoader && FictionDB && Extract ISBN && iOS reader applications && Goodreads && Barnes & Noble && Fantastic Fiction Adults && Quality Check && Modify ePub && Fantastic Fiction && Marvin XD && Count Pages
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 152, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
ImportError: cannot import name ConfigWidget

**Comment by Philantrop** [comment]
Go to Preferences | Advanced | Plugins | Device Interface plugins, select iOS reader applications.
Click Remove plugin.
Click Apply.
Go to Preferences | Advanced | Miscellaneous, click Open calibre configuration directory.
Open the plugins folder.
Delete iOS reader applications.json.
Delete the iOS_reader_applications_resources folder.
Restart calibre.
Then try installing the plugin(s) again.
