### ISSUE TITLE
can not get plugin for ios to download; can not use Marvin app

### ISSUE THREAD

**Issue by dttash** [Philantrop/calibre-ios-reader-applications#154]
I tried a few times to download IOS plugin for reader applications as directed so I can use MarvinXD app, but not able.  I get a message that says to post this:

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 712, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 390, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 557, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 551, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 910, in initialize
  File "calibre_plugins.ios_reader_apps.__init__", line 1239, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice
 failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 551, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 910, in initialize
  File "calibre_plugins.ios_reader_apps.__init__", line 1239, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
