### ISSUE TITLE
Plugin attempts to load older version of libimobiledevice library (.so.4 vs .so.5)

### ISSUE THREAD

**Issue by tomxtobin** [Philantrop/calibre-ios-reader-applications#156]
I'm running Calibre 2.12.0 under Arch Linux, with libimobiledevice 1.1.7 installed.

When attempting to install this plugin, I get the following error:
```
calibre, version 2.12.0
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/dialogs/plugin_updater.py", line 712, in _install_clicked
    plugin = add_plugin(zip_path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 390, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 557, in initialize_plugin
    %tb) + '\n'+tb)
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 551, in initialize_plugin
    p.initialize()
  File "calibre_plugins.ios_reader_apps.__init__", line 892, in initialize
  File "/usr/lib/calibre/calibre/devices/idevice/libimobiledevice.py", line 205, in __init__
    self.load_library()
  File "/usr/lib/calibre/calibre/devices/idevice/libimobiledevice.py", line 443, in load_library
    self.lib = cdll.LoadLibrary('libimobiledevice.so.4')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libimobiledevice.so.4: cannot open shared object file: No such file or directory
 failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 551, in initialize_plugin
    p.initialize()
  File "calibre_plugins.ios_reader_apps.__init__", line 892, in initialize
  File "/usr/lib/calibre/calibre/devices/idevice/libimobiledevice.py", line 205, in __init__
    self.load_library()
  File "/usr/lib/calibre/calibre/devices/idevice/libimobiledevice.py", line 443, in load_library
    self.lib = cdll.LoadLibrary('libimobiledevice.so.4')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libimobiledevice.so.4: cannot open shared object file: No such file or directory
```
On my system, libimobiledevice's library file is `libimobiledevice.so.5`, *not* `.so.4`, so the plugin fails to load.

**Comment by Philantrop** [comment]
As was correctly pointed out, this is not a plugin bug.
