### ISSUE TITLE
iOS Reader Application not installing

### ISSUE THREAD

**Issue by Xuyuan71** [Philantrop/calibre-ios-reader-applications#165]
Hi, the plug-in won't plug in.  Here are my specs and error message.  Yes, I reset the device and only one iProduct plugged in.  Thanks for your help.

*System*
Windows 8.1 64x
iPad Mini 2
calibre 2.14
Itunes 12.0.1.26
Marvin

*Error Message*
calibre, version 2.14.0
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 712, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 392, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 559, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 798, in initialize
TypeError: not enough arguments for format string
 failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 798, in initialize
TypeError: not enough arguments for format string

**Comment by maurerc** [comment]
Ditto with a Macintosh running 10.10.1

calibre, version 2.14.0
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/dialogs/plugin_updater.py", line 712, in _install_clicked
  File "site-packages/calibre/customize/ui.py", line 392, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 559, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 553, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 798, in initialize
TypeError: not enough arguments for format string
 failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 553, in initialize_plugin
  File "calibre_plugins.ios_reader_apps.__init__", line 798, in initialize
TypeError: not enough arguments for format string

**Comment by Philantrop** [comment]
During installation, no iDevice must be plugged in.
