### ISSUE TITLE
iOS Installation Problem

### ISSUE THREAD

**Issue by kchichester** [Philantrop/calibre-ios-reader-applications#167]
I upgrade to caibre 2.15.0 and updated the plugins. I got this error message:
(No device was connected.)
Windows 7 

calibre, version 2.15.0 32 bit)
ERROR: Install Plugin Failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart Calibre.

Traceback (most recent call last):
File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 712, in _install_clicked
File "site-packages\calibre\customize\ui.py", line 392, in add_plugin
File "site-packages\calibre\customize\ui.py", line 559, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
File "calibre_plugins.ios_reader_apps.__init__", line 916, in initialize
File "calibre_plugins.ios_reader_apps.__init__", line 1245, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice
failed with traceback:
Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
File "calibre_plugins.ios_reader_apps.__init__", line 916, in initialize
File "calibre_plugins.ios_reader_apps.__init__", line 1245, in _get_connected_device_info
InitialConnectionError: Unable to connect to iDevice

**Comment by Philantrop** [comment]
If you're still seeing this issue, please re-open this report.
