### ISSUE TITLE
iPad mini now Wifi

### ISSUE THREAD

**Issue by Hexe91** [Philantrop/calibre-ios-reader-applications#169]
calibre, version 2.22.0
FEHLER: Nicht abgefangener Fehler: <b>ImportError</b>:No module named PyQt4

calibre 2.22 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && FanFictionDownLoader && Ex Libris && Kobo Utilities && Count Pages && Hyphenate This! && KoboBooks && KoboTouchExtended && iOS reader applications && Manage Series && Annotations && Reading List && Read MP3 AudioBook metadata && KePub Output && Modify ePub
Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 789, in _configure_clicked
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "C:\Users\User\AppData\Roaming\calibre\plugins\iOS_reader_applications_resources\widgets\main_ui.py", line 10, in <module>
ImportError: No module named PyQt4

calibre, version 2.22.0
FEHLER: Nicht abgefangener Fehler: <b>ImportError</b>:cannot import name ConfigWidget

calibre 2.22 [64bit]  isfrozen: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && FanFictionDownLoader && Ex Libris && Kobo Utilities && Count Pages && Hyphenate This! && KoboBooks && KoboTouchExtended && iOS reader applications && Manage Series && Annotations && Reading List && Read MP3 AudioBook metadata && KePub Output && Modify ePub
Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 789, in _configure_clicked
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
ImportError: cannot import name ConfigWidget

**Comment by Philantrop** [comment]
Go to Preferences | Advanced | Plugins | Device Interface plugins, select iOS reader applications.
Click Remove plugin.
Click Apply.
Go to Preferences | Advanced | Miscellaneous, click Open calibre configuration directory.
Open the plugins folder.
Delete iOS reader applications.json.
Delete the iOS_reader_applications_resources folder.
Restart calibre.
Then try installing the plugin(s) again.
