### ISSUE TITLE
Calibre iOS Reader plugin not reconizing devices

### ISSUE THREAD

**Issue by Allayna** [Philantrop/calibre-ios-reader-applications#177]
iPhone 6 and iPad Air 2, both running iOS 8.3. 
Marvin app ver 2.8.1
Calibre 2.25
iOS Reader plugin 1.4.7.0.0

Following directions to 'customize plugin gives error "ImportError:No module named PyQt4"
calibre, version 2.25.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4

calibre 2.25  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Kindle and Mobipocket DeDRM && Ignoble Epub DeDRM && Inept Epub DeDRM && eReader PDB 2 PML && Inept PDF DeDRM && Marvin XD && iOS reader applications
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 493, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ios_reader_apps.config", line 26, in <module>
  File "C:\Users\Allayna\AppData\Roaming\calibre\plugins\iOS_reader_applications_resources\widgets\main_ui.py", line 10, in <module>
ImportError: No module named PyQt4

Debug Device Connection Log - 
calibre 2.25  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Kindle and Mobipocket DeDRM && Ignoble Epub DeDRM && Inept Epub DeDRM && Inept PDF DeDRM && eReader PDB 2 PML && Marvin XD && iOS reader applications
USB devices on system:
[u'usb\\root_hub20&vid8086&pid3b3c&rev0006',
 u'usb\\root_hub20&vid8086&pid3b34&rev0006',
 u'usb\\vid_0408&pid_2fb1&rev_0901',
 u'usb\\vid_0408&pid_2fb1&rev_0901&mi_00',
 u'usb\\vid_046d&pid_c52f&rev_2201',
 u'usb\\vid_046d&pid_c52f&rev_2201&mi_00',
 u'usb\\vid_046d&pid_c52f&rev_2201&mi_01',
 u'usb\\vid_0480&pid_0200&rev_0000',
 u'usb\\vid_05ac&pid_12a8&rev_0702',
 u'usb\\vid_05e3&pid_0608&rev_3298',
 u'usb\\vid_05e3&pid_0608&rev_3298',
 u'usb\\vid_0a5c&pid_21b2&rev_0539',
 u'usb\\vid_8087&pid_0020&rev_0000',
 u'usb\\vid_8087&pid_0020&rev_0000']
Traceback (most recent call last):
  File "site-packages\calibre\devices\scanner.py", line 85, in __call__
DriveError: No removable drives found
Drives detected:

No disabled plugins
Looking for devices of type: MTP_DEVICE
The Windows WPD service says there are no portable devices connected
 
Looking for devices of type: SMART_DEVICE_APP
All IP addresses {'{53229168-48BC-48A9-AE15-3BB98DC2DAA0}': [{'addr': '169.254.3.252'}, {'addr': '192.168.16.2'}], '{063786F4-6BC9-4033-AD73-5D9473CCFA67}': [{'netmask': '255.255.255.0', 'addr': '192.168.1.4', 'broadcast': '192.168.1.255'}], '{25C03C5C-A8A5-4401-9542-DE896CAE1711}': [{'addr': '169.254.53.107'}], '{98D9544B-A707-4FA9-89FC-422C9C6B5DC8}': [{'addr': '169.254.215.186'}], '{846EE342-7039-11DE-9D20-806E6F6E6963}': [{'netmask': '255.0.0.0', 'addr': '127.0.0.1', 'broadcast': '127.255.255.255'}], '{3EA39E01-5F70-42E3-89E4-4780B5004360}': [{'addr': '169.254.133.169'}]}
No device is connected
 
Looking for devices...
	u'usb\\vid_05ac&pid_12a8&rev_0702'
 
Devices possibly connected: None

**Comment by KatyaL** [comment]
There's a known compatibility problem with iOS 8.3. Nothing can be done about it at this time. http://www.mobileread.com/forums/showthread.php?t=241143&page=32
