### ISSUE TITLE
Plu

### ISSUE THREAD

**Issue by finros** [Philantrop/calibre-ios-reader-applications#179]
Note: Apologies if this comes in twice; net disconnected midway transmisstion and am resending.

Plugin won't accept customization. Error messages as ff:
![screen shot 2015-04-20 at 8 22 43 pm](https://cloud.githubusercontent.com/assets/12035158/7232654/729076cc-e7af-11e4-8eaf-4435ae2e3c78.png)

========
calibre, version 2.24.0
ERROR: Unhandled exception: <b>TypeError</b>:not all arguments converted during string formatting

calibre 2.24  isfrozen: True is64bit: True
Darwin-14.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.1.0', 'Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.2', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: K4PC, K4Mac, Kindle Mobi and Topaz DeDRM && Inept Epub DeDRM && Ignoble Epub DeDRM && Annotations && eReader PDB 2 PML && iOS reader applications && Inept PDF DeDRM
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 292, in customize_plugin
  File "site-packages/calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 503, in config_widget
  File "calibre_plugins.ios_reader_apps.config", line 85, in __init__
  File "/Users/sery/Library/Preferences/calibre/plugins/iOS_reader_applications_resources/widgets/marvin.py", line 168, in initialize
    self._log("Updating prefs to %d.%d.%d" % self.parent.version)
TypeError: not all arguments converted during string formatting
=============

**Comment by Tasilee** [comment]
I am running Calibre 2.43 on Windows 10.

I wanted to link Calibre and Marvin so installed the ios plug in. No problem.

I then went to customise it and got the PyQt4 error. Looked around for help and renamed the iOS_reader_applications_resources to _iOS_reader_applications_resources and tried to customise again but this time, I got the following

calibre, version 2.43.0
ERROR: Unhandled exception: <b>TypeError</b>:not all arguments converted during string formatting

calibre 2.43 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Goodreads Sync && KindleUnpack - The Plugin && iOS reader applications
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.ios_reader_apps.__init__", line 503, in config_widget
  File "calibre_plugins.ios_reader_apps.config", line 85, in __init__
  File "C:\Users\User\AppData\Roaming\calibre\plugins\iOS_reader_applications_resources\widgets\marvin.py", line 168, in initialize
TypeError: not all arguments converted during string formatting

Is it that the ios plug in does not work with the current version of Calibre? I thought this should have been a simple operation.
